<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Admin has been entered in UsernameTextBox]]>
    </line>
    <line>
      <![CDATA[admin123 has been entered in PasswordTextbox]]>
    </line>
    <line>
      <![CDATA[LoginButton has been clicked]]>
    </line>
    <line>
      <![CDATA[Mouse hovered on element PIM_Module]]>
    </line>
    <line>
      <![CDATA[employeeList_SubMenu has been clicked]]>
    </line>
    <line>
      <![CDATA[Employee_ID has not been clicked ]]>
    </line>
  </reporter-output>
  <suite started-at="2020-10-13T22:35:27Z" name="Suite" finished-at="2020-10-13T22:35:45Z" duration-ms="17995">
    <groups>
    </groups>
    <test started-at="2020-10-13T22:35:27Z" name="Test" finished-at="2020-10-13T22:35:45Z" duration-ms="17995">
      <class name="scripts.TC1_EditUserDetails">
        <test-method is-config="true" signature="handleTestScriptName(java.lang.reflect.Method)[pri:0, instance:scripts.TC1_EditUserDetails@740cae06]" started-at="2020-10-13T15:35:27Z" name="handleTestScriptName" finished-at="2020-10-13T15:35:27Z" duration-ms="5" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void scripts.TC1_EditUserDetails.editEmployeeDetails() throws java.lang.InterruptedException,org.apache.poi.EncryptedDocumentException,org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handleTestScriptName -->
        <test-method is-config="true" signature="precondition()[pri:0, instance:scripts.TC1_EditUserDetails@740cae06]" started-at="2020-10-13T15:35:27Z" name="precondition" finished-at="2020-10-13T15:35:34Z" duration-ms="7082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method signature="editEmployeeDetails()[pri:0, instance:scripts.TC1_EditUserDetails@740cae06]" started-at="2020-10-13T15:35:34Z" name="editEmployeeDetails" finished-at="2020-10-13T15:35:44Z" duration-ms="10254" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.fail(Assert.java:100)
	at generic.BasePage.clickOnElement(BasePage.java:71)
	at pom.LoginPage.clickOnEmployeeId(LoginPage.java:75)
	at scripts.TC1_EditUserDetails.editEmployeeDetails(TC1_EditUserDetails.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Admin has been entered in UsernameTextBox]]>
            </line>
            <line>
              <![CDATA[admin123 has been entered in PasswordTextbox]]>
            </line>
            <line>
              <![CDATA[LoginButton has been clicked]]>
            </line>
            <line>
              <![CDATA[Mouse hovered on element PIM_Module]]>
            </line>
            <line>
              <![CDATA[employeeList_SubMenu has been clicked]]>
            </line>
            <line>
              <![CDATA[Employee_ID has not been clicked ]]>
            </line>
          </reporter-output>
        </test-method> <!-- editEmployeeDetails -->
        <test-method is-config="true" signature="postcondition()[pri:0, instance:scripts.TC1_EditUserDetails@740cae06]" started-at="2020-10-13T15:35:44Z" name="postcondition" finished-at="2020-10-13T15:35:45Z" duration-ms="634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- scripts.TC1_EditUserDetails -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
